# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64cloudimagesubuntu'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box'

  config.cache.auto_detect = true
  config.cache.scope = :machine

  config.vm.provision :shell, inline: 'gem install chef --no-rdoc --no-ri'

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.cookbooks_path = [ 'cookbooks', '../..' ]

    chef.add_recipe 'git'
    chef.add_recipe 'vim-setup'

    clone_colo_manually = <<-HERE
      # clone manaully so the Vundle's BundleInstall command works from shell
      git clone https://github.com/Lokaltog/vim-distinguished.git ~/.vim/bundle/vim-distinguished
    HERE
    install_global_vim_plugin_dependencies = <<-HERE
      # for json formatting
      apt-get install -y libjson-xs-perl

      # python checker for Syntastic
      apt-get install -y python-pip
      pip install flake8

      # for TagBar
      apt-get install -y exuberant-ctags
      ln -s `which ctags-exuberant` /usr/local/bin/ctags
    HERE
    install_user_vim_plugin_dependencies = <<-HERE
      # for command-t
      cd ~/.vim/bundle/Command-T/ruby/command-t
      ruby extconf.rb
      make
    HERE
    chef.json = {
      vim_setup: {
        custom_bash_user: clone_colo_manually,
        custom_bash_once_after_vundle: install_global_vim_plugin_dependencies,
        custom_bash_user_after_vundle: install_user_vim_plugin_dependencies,
        dotfiles_repo: 'https://github.com/ikusalic/dotfiles.git',
        global: false,
        users: [ 'vagrant' ],
        use_vundle: true,
        vundle_timeout: 500,
      }
    }
  end
end
